### PR TITLE
Feature/error handling

### LINKED ISSUE #14: [FE] Add Error Boundary
As a user, I should be able to have errors on the site be displayed on to the page so I can understand what happened to the site.

Note: use ErrorBoundary.

### PR DESCRIPTION
**Pull request by laurelbonal**
# Description

Added Error boundary, ensured styling matches website. Added e2e testing for component. 

## Context

Added Error Boundary in App component, ensured light and dark mode working properly, added e2e testing for fallback component. Added routing to /error for the fallback page. This page will catch any uncaught errors and display them for the user. 

Fixes #14 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [x] Added e2e testing through Cypress, to test run command ```npm run e2e``` and run the FallBack spec 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KojinKuro** [comment]
Fixed merge conflicts. Looking over your code now :)

**Review by KojinKuro — COMMENTED** [review]
Looks good. Cleaned up your tailwind variables to match the conventions that ShadCN uses. Cleaned up Cypress testing to use our custom command instead of relying on classes.

I ran into a problem where refreshing the error page does not display anything. Would you be able to fix it so the user gets the error still somehow? Maybe we have to change how things are already working.

**Comment by laurelbonal** [comment]
Fixed the bug you were talking about but in the process I accidentally got rid of your changes to the fallback component for cypress testing. I will add them back

**Comment by KojinKuro** [comment]
Fixed your Cypress testing to handle the new URL changing. I think you forgot to update it after adding the feature requested :) Looks great besides that!

**Pull request merged**
